### ISSUE TITLE
Tiles failed to load. 

### ISSUE THREAD

**Issue by rsignell-usgs** [kylebarron/usgs-topo-mosaic#15]
https://kylebarron.dev/usgs-topo-mosaic/#12.89/37.75978/-119.76413

Tried today and tiles failed to load.  

Is this user error somehow or a temporary or longer-term problem?

**Comment by kylebarron** [comment]
https://twitter.com/kylebarron2/status/1412494170107920389?s=21

**Comment by rsignell-usgs** [comment]
😿
